### ISSUE TITLE
cisco_vpc_domain creates error "No set of title patterns matched the title"

### ISSUE THREAD

**Issue by henriots** [cisco/cisco-network-puppet-module#515]
Hello!

Using "cisco_vpc_domain" module creates this error:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: No set of title patterns matched the title "CREATE_VPC_DOMAIN".`

Here's is manifest class:

```
class vpc_configuration {
	require overall::feature_leaf
	cisco_vpc_domain { "CREATE_VPC_DOMAIN":
		domain => $vpc_id,
	}
}
```
Error message doesn't give much to go on, other modules are working fine. Tried even without $vpc_id variable and just a number.

**Comment by mikewiebe** [comment]
Hello @henriots thanks for posting the issue.  The title pattern for this resource must be an integer.  Can you try the following format instead?

```puppet
class vpc_configuration {
	require overall::feature_leaf
	cisco_vpc_domain { "${vpc_id}":
		ensure => present,
	}
}
```

Here is an example from our demo manifest collection

https://github.com/cisco/cisco-network-puppet-module/blob/develop/examples/cisco/demo_vpc_domain.pp#L46

**Comment by henriots** [comment]
Hello!

That's correct. My bad. Still learning Puppet.

Thanks alot!

**Comment by henriots** [comment]
Didn't want to create a new issue, so I'll add it to here. I'm following your posted manifest. First I though I screwed again something up, but then I just copied your posted example. I get the same error message anyways.

`class vpc_configuration {
	require overall::feature_leaf
	$vpc_id="200"
	
	cisco_vpc_domain { "${vpc_id}":
		ensure => present,
		peer_keepalive_dest => '10.100.65.241',
		peer_keepalive_hold_timeout => 'default',
		peer_keepalive_interval => 'default',
		peer_keepalive_interval_timeout => 5,
		peer_keepalive_precedence => 6,
		peer_keepalive_src => '10.100.65.242',
		peer_keepalive_udp_port => 3200,
		peer_keepalive_vrf => 'management',
		peer_gateway => true,
	}
	
    cisco_interface_channel_group { 'Ethernet1/1':
      require       => Cisco_vpc_domain[$vpc_id],
      channel_group => 10,
    }

    cisco_interface { 'port-channel10' :
      switchport_mode => 'trunk',
      vpc_id          => 5,
      shutdown        => false,
      require         => Cisco_interface_channel_group['Ethernet1/1'],
    }

    cisco_interface_channel_group { 'Ethernet1/2':
      require       => Cisco_vpc_domain[$vpc_id],
      channel_group => 100,
    }

    cisco_interface { 'port-channel100' :
      switchport_mode => 'trunk',
      # Note: peer-link is incompatible with NVE features
      vpc_peer_link   => true,
      shutdown        => false,
      require         => Cisco_interface_channel_group['Ethernet1/2'],
    }
}`

I get a error message:
``Notice: /Stage[main]/Vpc_configuration/Cisco_interface[port-channel100]/vpc_peer_link: vpc_peer_link changed 'false' to 'true'
`
`Error: /Stage[main]/Vpc_configuration/Cisco_interface[port-channel100]: Could not evaluate: undefined local variable or method `vpc_peerlink' for #<Cisco::Interface:0xb4c696c>``

**Comment by mikewiebe** [comment]
@henriots Which cisco puppet module version are you using?

**Comment by henriots** [comment]
> @henriots Which cisco puppet module version are you using?
> 
> Also could you run `puppet agent -t --trace` and send the output?
Here is version:
/etc/puppetlabs/code/environments/production/modules
├── puppetlabs-ciscopuppet (v1.10.0)
└── puppetlabs-netdev_stdlib (v0.16.0)

Here is output of --trace
```
Notice: /Stage[main]/Vpc_configuration/Cisco_interface[port-channel100]/vpc_peer_link: vpc_peer_link changed 'false' to 'true'
Error: /Stage[main]/Vpc_configuration/Cisco_interface[port-channel100]: Could not evaluate: undefined local variable or method `vpc_peerlink' for #<Cisco::Interface:0xacc03bc>
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/cisco_node_utils-1.10.0/lib/cisco_node_utils/interface.rb:2028:in `vpc_peer_link='
/opt/puppetlabs/puppet/cache/lib/puppet/provider/cisco_interface/cisco.rb:256:in `block in properties_set'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/cisco_interface/cisco.rb:252:in `each'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/cisco_interface/cisco.rb:252:in `properties_set'
/opt/puppetlabs/puppet/cache/lib/puppet/provider/cisco_interface/cisco.rb:387:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1006:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:25:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:233:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:249:in `eval_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `block (2 levels) in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:507:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:506:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:118:in `traverse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:154:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:222:in `block in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:155:in `with_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:146:in `as_logging_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:221:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:171:in `block in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:224:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:223:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:170:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:343:in `run_internal'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:221:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:306:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:195:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:58:in `block (5 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:57:in `block (4 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent/locker.rb:21:in `lock'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:51:in `block (3 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:118:in `with_client'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:48:in `block (2 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:85:in `run_in_fork'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:47:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:179:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:179:in `controlled_run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:45:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:360:in `onetime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:338:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:662:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:375:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
```

**Comment by saichint** [comment]
@henriots We did find a problem in the code. There was a typo error. 
I opened a PR (not yet merged into the develop branch)
https://github.com/cisco/cisco-network-node-utils/pull/598

You can take this change and patch up your cisco_node_utils and build a gem and try it for your manifest.
The other way is to put the fix on your agent directly at:
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/cisco_node_utils-1.10.0/lib/cisco_node_utils/interface.rb
and then try it.

Let us know if things are fine for you with this fix.
